# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: fix-byte-order-marker
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: ""
      hooks:
          - id: mypy
    - repo: https://gitlab.com/PyCQA/flake8
      rev: "3.8.4"
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/isort
      rev: "5.6.4"
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.43.0
      hooks:
          - id: terraform_fmt
