version: "3.7"

services:
  server:
    image: kubac65/micro-brew-server:latest
    ports:
      - "52100"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 8086
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DB_DATABASE: micro_brew

  db:
    image: influxdb:latest
    networks:
      - backend
    volumes:
      - data-volume:/var/lib/db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      INFLUX_DB: micro-brew

networks:
  backend:
  frontend:
volumes:
  data-volume: