version: '3.7'

services:
  server:
    image: micro-brew-server:latest
    build:
      context: .
  timeseries-db:
    ports:
      - "8086:8086"
  brew-db:
    ports:
      - "5984:5984"

  chronograf:
    image: chronograf:latest
    ports:
      - "8888:8888"
    networks:
      - backend