version: "3.7"

services:
  server:
    image: kubac65/micro-brew-server:latest
    hostname: server
    ports:
      - "52100:52100"
    networks:
      - backend
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 8086
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: micro-brew

  db:
    image: influxdb:latest
    hostname: db
    ports:
      - "8086:8086"
      - "8083:8083"
    networks:
      - backend
    volumes:
      - data-volume:/var/lib/db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      INFLUX_DB: micro-brew
      INFLUX_ADMIN_ENABLED: "true"

networks:
  backend:
volumes:
  data-volume: