version: "3.7"

services:
  server:
    image: kubac65/micro-brew-server:latest
    ports:
      - "52100:52100" # Expose port 52100 for the controllers to connect to
    networks:
      - backend
    depends_on:
      - timeseries-db
      - brew-db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      TS_DB_HOST: timeseries-db
      TS_DB_PORT: 8086
      TS_DB_USERNAME: root
      TS_DB_PASSWORD: root
      TS_DB_DATABASE: micro-brew
      BR_DB_HOST: brew-db
      BR_DB_PORT: 5984
      BR_DB_USERNAME: root
      BR_DB_PASSWORD: root
      BR_DB_DATABASE: micro-brew

  timeseries-db:
    image: influxdb:latest
    networks:
      - backend
    volumes:
      - ts-db-data-volume:/var/lib/db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      INFLUX_DB: micro-brew

  brew-db:
    image: couchdb:latest
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - br-db-data-volume:/opt/couchdb/data

networks:
  backend:
volumes:
  ts-db-data-volume:
  br-db-data-volume: